### ISSUE TITLE
Returns 'NoneType' object has no attribute 'image_set' on Index page

### ISSUE THREAD

**Issue by TechNech** [abecam/thefiltershop#1]
Error Image:
![image](https://github.com/abecam/thefiltershop/assets/4355289/1b39160d-045f-4e7d-a9f0-546793d25255)

Error from File: thefiltershop_main/views/main.py (Line 35)
![image](https://github.com/abecam/thefiltershop/assets/4355289/05fe6d8f-f66e-4b3f-aa36-112988db95d9)

**Comment by abecam** [comment]
Should be fixed by commit 6767844

**Comment by TechNech** [comment]
Resolved.
